### ISSUE TITLE
It seems that the examples are broken

### ISSUE THREAD

**Issue by pedroapfilho** [kentcdodds/react-testing-library-examples#10]
I'll rewrite them with `hooks` and fix them all. Probably I'll add some other tests on it too. Any ideas for new tests?

**Comment by kentcdodds** [comment]
Yes, if you could rewrite them all to use hooks that would be sweet. And any other tests you want to add/change would be welcome. Happy to review :)

**Comment by pedroapfilho** [comment]
I'll work on it this weekend, and I'll link the PR here!

**Comment by pedroapfilho** [comment]
It seems that the tests are not cleaning up after each test, do you have any idea of what could be happening?

**Comment by kentcdodds** [comment]
I'm guessing it's a problem with codesandbox. Probably related to this: https://github.com/codesandbox/codesandbox-client/issues/3580

**Comment by ryota-murakami** [comment]
@kentcdodds Holy shit timing XD
I've just clone repo and run test in local that works well so I got strange feeling 😅

<img width="882" alt="Screen Shot 2020-03-04 at 12 28 43" src="https://user-images.githubusercontent.com/5501268/75842581-0ab1c200-5e14-11ea-98f3-90206da524ad.png">

**Comment by pedroapfilho** [comment]
I literally spent 4h on it, thinking that I was too dumb to understand why that was happening 😅.

What I'll do then is cloning the app to my local machine, refactor them a little bit and make a PR to submit the changes. I'll not wait for the other fixes to be finished.

**Comment by cmacdonnacha** [comment]
Hey, do you know if this has been merged?

**Comment by pedroapfilho** [comment]
@cmacdonnacha not yet, it seems that this one: https://github.com/codesandbox/codesandbox-client/issues/3580 has to be fixed first
