### ISSUE TITLE
jest binary global not currents standard

### ISSUE THREAD

**Issue by ojnc** [kentcdodds/react-testing-library-examples#12]
package.json still has **"test": "jest",** but should be **"test": "react-scripts test",**

Most people esp. new comers use **create-react-app** which installs jest in the innards
so if anyone runs **yarn test** it with your clone it does not work until package.json is edited

Please fix if relevant

**Comment by kentcdodds** [comment]
Hi @ojnc,

We have a custom jest configuration for this project specifically. This isn't intended to be an example of configuration or anything. Just for how to write certain types of tests. Thanks anyway.
