### ISSUE TITLE
Both "package-lock.json" and "yarn.lock" are included

### ISSUE THREAD

**Issue by kettanaito** [kentcdodds/react-testing-library-examples#13]
I've noticed that this repo has both NPM and Yarn lockfiles committed. Is this intentional?

It's generally not recommended, because lockfiles always differ (unless you run _both_ `npm install` and `yarn add` for each dependency change), which results into different set of 3rd and 4th party dependencies being installed for users.

**Comment by kettanaito** [comment]
This also complicated a contribution process: if I wish to add a dependency, should I use NPM or Yarn? 🤔

**Comment by kentcdodds** [comment]
Those should be in the gitignore. You should be able to use whatever.

**Comment by kettanaito** [comment]
Should we remove the files from Git if they are ignored?

<img width="634" alt="Screen Shot 2020-06-06 at 10 35 22" src="https://user-images.githubusercontent.com/14984911/83939994-732c8880-a7e1-11ea-8935-8b6b7e74d1d7.png">

**Comment by kentcdodds** [comment]
Yeah, sorry, that's what I meant. Could you remove them and make sure they're in the gitignore?

**Comment by kettanaito** [comment]
Done!
