### ISSUE TITLE
All examples are failing in CodeSandbox

### ISSUE THREAD

**Issue by nerfologist** [kentcdodds/react-testing-library-examples#20]
Hello,
I'm writing just to report that all of the examples are currently failing [in CodeSandbox](https://codesandbox.io/s/github/kentcdodds/react-testing-library-examples), while they are still running perfectly on my local machine.

![Screenshot 2020-09-17 at 10 44 41](https://user-images.githubusercontent.com/1634023/93447558-d2b32d80-f8d2-11ea-8ae5-427f23ef6bba.png)

This is the reported error:
```
Identifier 'test' has already been declared

SyntaxError: Identifier 'test' has already been declared
    at eval (<anonymous>)
    at Eo (https://codesandbox.io/static/js/sandbox.6079041c3.js:1:201748)
    ...
```

I noticed this error while trying to develop my own CodeSandbox with tests involving `@testing-library/react` and `@testing-library/jest-dom`; when I tried this reference CodeSandbox I got the same error.

HTH

**Comment by marr** [comment]
I'm not seeing the tests run at all in CodeSandbox. Is there some configuration update needed or is this issue on CodeSandboxes side?

**Comment by kentcdodds** [comment]
I've pretty much given up on Codesandbox running tests reliably. :(

**Comment by nerfologist** [comment]
Hello! The original report was from some time ago, I tried now and it's not running the test suite at all.

Will run in local!

Thanks for your answers.

**Comment by marr** [comment]
Thanks Ken. I emailed CodeSandbox, would be nice if they did work there. I wanted to create an easily sharable repro case for some mocking questions I have. Was trying to get help in discord without luck. Maybe a shareable link/repo would make it easier for people to assist.

**Comment by kentcdodds** [comment]
You're not going to get mocking working in codesandbox I'm afraid. That's never been supported. You'll have to do that locally.
