### ISSUE TITLE
Code Sandbox Example Tests: Expect is not Defined

### ISSUE THREAD

**Issue by alexkrolick** [kentcdodds/react-testing-library-examples#4]
Reported at https://github.com/alexkrolick/testing-library-docs/issues/37

**Comment by kentcdodds** [comment]
I think this is a codesandbox bug and I'm pretty sure it's already reported.

**Comment by alexkrolick** [comment]
Should probably move everything failing into __local-tests__

**Comment by kentcdodds** [comment]
I think it'd be better to fix the codesandbox issue...

**Comment by alexkrolick** [comment]
@compuives 👀
