### ISSUE TITLE
Test Suites 7 failed 4 passed 11 total

### ISSUE THREAD

**Issue by NorfeldtAbtion** [kentcdodds/react-testing-library-examples#9]
What an awesome collection of tests - really good job.

There is however a lot of them that are failing (which might be due to some codesandbox issue)

<img width="772" alt="Screenshot 2020-01-07 at 09 28 01" src="https://user-images.githubusercontent.com/53769763/71880201-0dec4280-3130-11ea-92fc-b4c4b4519e2b.png">

**Comment by kentcdodds** [comment]
Yeah, this is a codesandbox issue. If I make a change in any file all the tests start passing. You can feel free to open an issue on codesandbox.

Thanks!
